### ISSUE TITLE
What are the minimum requirements?

### ISSUE THREAD

**Issue by Zorgle** [BizArk/BizArk3#6]
I was unable to pull the nuget package with Visual Studio 2012.

I tried cloning the BizArk3 github project and compiling it with Visual Studio 2015, and it failed to compile, reporting syntax errors on a line that contained "?? throw new Exception..."

What version of Visual Studio is required for the latest? What version is required for BizArk2? 

Is there a version of BizArk that can be used with Visual Studio 2012?

Thanks for any info...

**Comment by bbrewder** [comment]
I am not sure if BizArk v2 would compile or not in VS 2012 (I haven't tried compiling it in a long time). 

BizArk v3 does require VS 2017 to compile (it uses some new, fancy features). I currently have it compiling for .Net 4.5. If you want, you can fork BizArk v3 and try compiling it for which ever version of .Net you need. I would recommend using VS 2017 (you should be able to use the free community edition). There is likely a bunch of code you will need to change or remove to get it to compile, but, depending on what you are doing and which version of .Net you need to compile to, it will probably still be mostly functional.
