### ISSUE TITLE
CmdLineOptions is not optional for ParseArgs<T>( string queryString, CmdLineOptions options = null )

### ISSUE THREAD

**Issue by FraserConnolly** [BizArk/BizArk3#8]
The querryString overload of the ParseArgs function (like the others) in BaCon allows for options to be null, however in QueryStringToArgs the options parameter is used before being checked to see if it is null thus causes an unhanded exception.

Please see line 334 for the offending call.

[ Line 334 BaCon.cs ](https://github.com/BizArk/BizArk3/blob/88d32682ae32d7c18bf196944836f52cc0fa9f8c/BizArk.ConsoleApp/BaCon.cs#L334)

I can work around this problem just by initialising a new CmdLineOptions object and passing that into ParseArgs so I've got no urgency to see this fixed I just wanted to point out this issue with an otherwise really neat library.

Thanks

**Comment by bbrewder** [comment]
Thanks for reporting the issue. I've got a fix if you want it. Just upgrade to the latest version of BizArk.ConsoleApp.
